In [4]:
import numpy as np
arr1 = np.array([1,3,2,4])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)

[1 3 2 4]
<class 'numpy.ndarray'>
int64
(4,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
np.arange(0,10,2).reshape(5,1)   
np.ones((1,2)) 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
import pandas as pd
data = [1,2,3,4]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
dtype: int64