In [1]:
import numpy as np
arr1 = np.array([1,3,2,4])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)

[1 3 2 4]
<class 'numpy.ndarray'>
int64
(4,)


In [2]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [3]:
np.arange(0,10,2).reshape(5,1)   
np.ones((1,2)) 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
import pandas as pd
data = [1,2,3,4]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
data = {'a':1,'b':2,'c':3}
print(pd.Series(data))

a    1
b    2
c    3
dtype: int64


In [6]:
data = [1,2,3,4]
index = ['a','b','c','d']
pd.Series(data,index)

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
data = {
    "name" : ["siva","tarun","chitti"],
    "age" : [23,24,25],
    "city" : ["chennai","bangalore","hyderabad"]
}

data = pd.DataFrame(data,index=[1,2,3])
data

name  age       city
1    siva   23    chennai
2   tarun   24  bangalore
3  chitti   25  hyderabad

In [10]:
data = [
    {"name":"siva","age":23,"city":"chennai"},
    {"name":"siva","age":24,"city":"bangalore"},
    {"name":"siva","age":23,"city":"hyderabad"}
]

df = pd.DataFrame(data)

In [15]:
df.at[2,"age"] # gives the specified index column value specified

np.int64(23)

In [17]:
df.iat[2,2] # gets the value at specified index

'hyderabad'

In [18]:
df["salry"] =[100,200,300]

In [19]:
df

name  age       city  salry
0  siva   23    chennai    100
1  siva   24  bangalore    200
2  siva   23  hyderabad    300

In [21]:
df.drop('salary') # by default axis is 0 that is x-axis

KeyError: "['salary'] not found in axis"

In [24]:
df.drop('salry',axis=1) # it will not remove from the main df

name  age       city
0  siva   23    chennai
1  siva   24  bangalore
2  siva   23  hyderabad